name: Auto-Generate Objects and Schemas

on:
  pull_request:

permissions:
  contents: write

jobs:
  autogen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: regenerate all schema and extension-definition files
        run: |
          pip install .
          rm -rf automodel_generated/
          python generate_all.py

      - name: Commit & push generated changes
        run: |
          git remote set-url origin "https://oauth2:${{github.token}}@github.com/${{github.repository}}.git"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          
          if [ -z "$(git status --porcelain)" ]; then
            echo "âœ… No generated changes to commit."
            exit 0
          fi
          git commit -m "chore: auto-generate data  "
          git push origin ${{ github.head_ref }}
